on:
  github:
    branches:
      only: main

jobs:

  dang:
    resources:
      instance-type: C5
    uses: script@v1
    with:
      script: echo Hello
      image: paperspace/transformers-gpu:0.4.0
