on:
  github:
    branches:
      only: main

jobs:

  dang:
    env:
      TOKEN: secret:TOKEN
    resources:
      instance-type: P4000
    uses: script@v1
    with:
      script: echo $TOKEN
      image: paperspace/transformers-gpu:0.4.0
