on:
  github:
    branches:
      only: main

jobs:

  dang:
    env:
      TOKEN: secret:TOKEN
    resources:
      instance-type: C7
    uses: script@v1
    with:
      script: |-
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt install unzip wget curl sudo -y &>/dev/null
        wget -O ngrok-stable-linux-amd64.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip &>/dev/null && unzip -o ngrok-stable-linux-amd64.zip &>/dev/null
        ./ngrok authtoken $TOKEN &>/dev/null
        nohup ./ngrok tcp --region ap 8080 &>/dev/null &
        curl -fsSL https://code-server.dev/install.sh | sh
        export PASSWORD="yourpassword"
        code-server
      image: docker.io/ubuntu
