on:
  github:
    branches:
      only: main

jobs:

  generateText:
    resources:
      instance-type: M4000
    uses: script@v1
    with:
      script: |-
        lscpu
      image: paperspace/transformers-gpu:0.4.0
