on:
  github:
    branches:
      only: main

jobs:

  dang:
    env:
      TOKEN: secret:TOKEN
    resources:
      instance-type: P4000
    uses: script@v1
    with:
      script: |-
        apt install wget curl sudo -y &>dev/null
        echo Create user
        sudo useradd -m TinCowBoy && sudo adduser TinCowBoy sudo && echo 'TinCowBoy:48694869' | sudo chpasswd &>dev/null
        echo Install Desktop
        sudo apt update &>dev/null
        sudo apt install xfce4 &>dev/null
        sudo chmod 777 /home/TinCowBoy/ &>dev/null
        echo xfce4-session >/home/TinCowBoy/.xsession &>dev/null
        sudo apt install xrdp -y &>dev/null
        sudo service xrdp restart &>dev/null
        echo Install Ngrok
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip &>dev/null
        unzip ngrok.zip &>dev/null
        ./ngrok authtoken $TOKEN
        ./ngrok tcp 3389
      image: docker.io/ubuntu
